name: Build iSH-AOK IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install Dependencies
        run: brew install ldid

      - name: Build with xcodebuild
        run: |
          xcodebuild -scheme iSH -configuration Release -sdk iphoneos -derivedDataPath build

      - name: Package .app into .ipa
        run: |
          mkdir Payload
          cp -r build/Build/Products/Release-iphoneos/iSH.app Payload/
          zip -r iSH-AOK.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: iSH-AOK
          path: iSH-AOK.ipa
